apiVersion: apps/v1
kind: Deployment
metadata:
  name: certification-service
  namespace: assessment-ms
  labels:
    app: certification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certification-service
  template:
    metadata:
      labels:
        app: certification-service
    spec:
      containers:
        - name: certification-service
          image: fatmasboui/certification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/certification_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: certification-service
  namespace: assessment-ms
spec:
  selector:
    app: certification-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
