spring.application.name=notification-service
server.port=8083

# Eureka (si tu veux l?enregistrer)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.import-check.enabled=false

# Si tu ne veux pas enregistrer sur Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
