CREATE DATABASE IF NOT EXISTS assessment_db;
CREATE DATABASE IF NOT EXISTS career_db;
CREATE DATABASE IF NOT EXISTS certification_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS quiz_db;
