# -------------------
# Port et nom de l'application
# -------------------
server.port=8089
spring.application.name=api-gateway

# -------------------
# Eureka
# -------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# -------------------
# Gateway
# -------------------
spring.cloud.gateway.discovery.locator.enabled=true
spring.main.web-application-type=reactive

# -------------------
# Routes Gateway
# -------------------

# Assessment Service
spring.cloud.gateway.routes[0].id=assessment-service
spring.cloud.gateway.routes[0].uri=lb://assessment-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/assessment-api/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/assessment-api/(?<segment>.*), /$\{segment}

# Job Service
spring.cloud.gateway.routes[1].id=job-service
spring.cloud.gateway.routes[1].uri=lb://job-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/job-offers/**,/applications/**

# Certification Service
spring.cloud.gateway.routes[2].id=certification-service
spring.cloud.gateway.routes[2].uri=lb://certification-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/certifications/**,/certification-exams/**,/certification-results/**,/questions/**,/answers/**

# Notification Service
spring.cloud.gateway.routes[3].id=notification-service
spring.cloud.gateway.routes[3].uri=lb://notification-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/ws/**

# Quiz Service
spring.cloud.gateway.routes[4].id=quiz-service
spring.cloud.gateway.routes[4].uri=lb://quiz-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/quizzes/**,/quiz-questions/**,/game-sessions/**,/scores/**,/ws-quiz/**

# User Management Service
spring.cloud.gateway.routes[5].id=user-management-service
spring.cloud.gateway.routes[5].uri=lb://user-management-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/users/**

# Auth Service
spring.cloud.gateway.routes[6].id=auth-service
spring.cloud.gateway.routes[6].uri=lb://auth-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/auth/**,/AUTH-SERVICE/**