# -------------------
# Port et nom de l'application
# -------------------
server.port=8089
spring.application.name=api-gateway

# -------------------
# Eureka
# -------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# -------------------
# Gateway
# -------------------
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.config.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.web-application-type=reactive

# -------------------
# Routes Gateway
# -------------------

# Exam Service
spring.cloud.gateway.routes[0].id=exam-service
spring.cloud.gateway.routes[0].uri=lb://exam-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/international-exams/**,/exam-results/**,/exam-questions/**

# Job Service
spring.cloud.gateway.routes[1].id=job-service
spring.cloud.gateway.routes[1].uri=lb://job-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/job-offers/**,/applications/**

# Certification Service
spring.cloud.gateway.routes[2].id=certification-service
spring.cloud.gateway.routes[2].uri=lb://certification-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/certifications/**,/certification-exams/**,/certification-results/**,/questions/**,/answers/**

# Notification Service
spring.cloud.gateway.routes[3].id=notification-service
spring.cloud.gateway.routes[3].uri=lb://notification-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/ws/**

# Quiz Service
spring.cloud.gateway.routes[4].id=quiz-service
spring.cloud.gateway.routes[4].uri=lb://quiz-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/quizzes/**,/quiz-questions/**,/game-sessions/**,/scores/**

# -------------------
# CORS global pour Angular
# -------------------
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600